// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_tui_app
void run_tui_app(Rcpp::List ui_list, Rcpp::List state_list, Rcpp::List handlers);
RcppExport SEXP _rtui_run_tui_app(SEXP ui_listSEXP, SEXP state_listSEXP, SEXP handlersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type ui_list(ui_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type state_list(state_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type handlers(handlersSEXP);
    run_tui_app(ui_list, state_list, handlers);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtui_run_tui_app", (DL_FUNC) &_rtui_run_tui_app, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtui(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
