// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// runTuiApp
void runTuiApp(Rcpp::List uiList, Rcpp::List stateList, Rcpp::List handlers, std::string overflow);
RcppExport SEXP _rtui_runTuiApp(SEXP uiListSEXP, SEXP stateListSEXP, SEXP handlersSEXP, SEXP overflowSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type uiList(uiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type stateList(stateListSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type handlers(handlersSEXP);
    Rcpp::traits::input_parameter< std::string >::type overflow(overflowSEXP);
    runTuiApp(uiList, stateList, handlers, overflow);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtui_runTuiApp", (DL_FUNC) &_rtui_runTuiApp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtui(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
