# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_tui_app <- function(ui_list, state_list, handlers) {
    invisible(.Call(`_rtui_run_tui_app`, ui_list, state_list, handlers))
}

