# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal helper `runTuiApp`.
#'
#' Calls the C++ event loop bridge with UI, state, and handlers.
#'
#' @param uiList Serialized UI component list passed to C++.
#' @param stateList Current application state list with `input` and `output`.
#' @param handlers Named list of event handlers keyed by input id.
#'
#' @return Invisibly returns `NULL`.
#'
#' @keywords internal
#' @noRd
runTuiApp <- function(uiList, stateList, handlers) {
    invisible(.Call(`_rtui_runTuiApp`, uiList, stateList, handlers))
}

